# Generated by Django 3.2 on 2021-05-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userImages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
