# Generated by Django 3.2 on 2021-05-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userImages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
